# Generated by Django 5.2.6 on 2025-09-15 15:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('boots', 'Football Boots'), ('ball', 'Football'), ('accessories', 'Accessories'), ('training', 'Training Equipment'), ('merchandise', 'Merchandise')], default='jersey', max_length=30)),
                ('is_featured', models.BooleanField()),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
