# Generated by Django 5.2.6 on 2025-09-14 11:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('boots', 'Football Boots'), ('ball', 'Football'), ('accessories', 'Accessories'), ('training', 'Training Equipment'), ('merchandise', 'Merchandise')], default='jersey', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
